body {
    background-color: #fef9c3;
    font-family: Arial, sans-serif;
    text-align: center;
    margin: 0;
    padding: 0;
}

.container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100vh;
}

h1 {
    color: #ff5733;
    font-size: 2em;
    margin-bottom: 10px;
}

img {
    width: 300px;
    border-radius: 10px;
    box-shadow: 5px 5px 10px rgba(0, 0, 0, 0.3);
}

.mensaje {
    font-size: 0.8em;
    color: #555;
    margin-top: 10px;
}
